

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 50 --name animalweb_step_50_pool_mouth_add_per_60_10_v1 --l-threshold 0.6 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_50_pool_mouth_add_per_60_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_50_pool_mouth_add_per_60_10_v1_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 25 --name animalweb_step_25_pool_mouth_add_per_60_10_v1 --l-threshold 0.6 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_25_pool_mouth_add_per_60_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_25_pool_mouth_add_per_60_10_v1_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 10 --name animalweb_step_10_pool_mouth_add_per_60_10_v1 --l-threshold 0.6 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_10_pool_mouth_add_per_60_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_10_pool_mouth_add_per_60_10_v1_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 150 --name animalweb_step_150_pool_mouth_add_per_60_10_v1 --l-threshold 0.6 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_150_pool_mouth_add_per_60_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_150_pool_mouth_add_per_60_10_v1_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 250 --name animalweb_step_250_pool_mouth_add_per_60_10_v1 --l-threshold 0.6 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_250_pool_mouth_add_per_60_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_250_pool_mouth_add_per_60_10_v1_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 300 --name animalweb_step_300_pool_mouth_add_per_60_10_v1 --l-threshold 0.6 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_300_pool_mouth_add_per_60_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_300_pool_mouth_add_per_60_10_v1_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 350 --name animalweb_step_350_pool_mouth_add_per_60_10_v1 --l-threshold 0.6 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_350_pool_mouth_add_per_60_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_350_pool_mouth_add_per_60_10_v1_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 400 --name animalweb_step_400_pool_mouth_add_per_60_10_v1 --l-threshold 0.6 --total-steps 10000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_400_pool_mouth_add_per_60_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_400_pool_mouth_add_per_60_10_v1_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 500 --name animalweb_step_500_pool_mouth_add_per_60_10_v1 --l-threshold 0.6 --total-steps 10000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_500_pool_mouth_add_per_60_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_500_pool_mouth_add_per_60_10_v1_best.pth.tar


# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 600 --name animalweb_step_600_pool_mouth_add_per_60_10_v1 --l-threshold 0.6 --total-steps 10000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_600_pool_mouth_add_per_60_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_600_pool_mouth_add_per_60_10_v1_best.pth.tar


# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 700 --name animalweb_step_700_pool_mouth_add_per_60_10_v1 --l-threshold 0.6 --total-steps 10000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_700_pool_mouth_add_per_60_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_700_pool_mouth_add_per_60_10_v1_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 800 --name animalweb_step_800_pool_mouth_add_per_60_10_v1 --l-threshold 0.6 --total-steps 10000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_800_pool_mouth_add_per_60_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_800_pool_mouth_add_per_60_10_v1_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 600 --name animalweb_step_600_pool_mouth_add_per_60_25_10_v1 --l-threshold 0.6 --f-threshold 2.5 --total-steps 10000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_600_pool_mouth_add_per_60_25_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_600_pool_mouth_add_per_60_25_10_v1_best.pth.tar
# python train_pool_add_mouth.py --cfg ./experiment/1.yaml --update-steps 600 --name animalweb_step_600_pool_mouth_add_per_60_25_v3_8 --l-threshold 0.6 --f-threshold 2.5 --total-steps 10000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/v3_8/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_600_pool_mouth_add_per_60_25_v3_8_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_600_pool_mouth_add_per_60_25_v3_8_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/40.yaml --update-steps 600 --name animalweb_step_600_pool_mouth_add_per_60_35_40_v1 --l-threshold 0.6 --f-threshold 3.5 --total-steps 5000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/train_40/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_600_pool_mouth_add_per_60_35_40_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_600_pool_mouth_add_per_60_35_40_v1_best.pth.tar
python train_pool_add_mouth.py --cfg ./experiment/40.yaml --update-steps 600 --name animalweb_step_600_pool_mouth_add_per_60_35_40_v1 --l-threshold 0.05 --f-threshold 0.2 --total-steps 5000 --hptsfile humanfox.json --heightfile metadata.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/train_40/latest.pth

# python train_pool_add_mouth.py --cfg ./experiment/horse.yaml --update-steps 600 --name animalweb_step_600_pool_mouth_add_per_60_25_horse_10 --l-threshold 0.6 --f-threshold 5 --total-steps 5000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/horse_10/best.pth
# python test.py --cfg ./experiment/horse.yaml --seed 5 --name animalweb_step_600_pool_mouth_add_per_60_25_horse_10_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_600_pool_mouth_add_per_60_25_horse_10_best.pth.tar
# python train_pool_add_mouth.py --cfg ./experiment/70.yaml --update-steps 600 --name animalweb_step_600_pool_mouth_add_per_60_25_70 --l-threshold 0.6 --f-threshold 2.5 --total-steps 10000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/70_V1/best.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_600_pool_mouth_add_per_60_25_70_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_600_pool_mouth_add_per_60_25_70_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 600 --name animalweb_step_600_pool_mouth_add_per_60_20_10_v1 --l-threshold 0.6 --f-threshold 2.0 --total-steps 10000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_600_pool_mouth_add_per_60_20_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_600_pool_mouth_add_per_60_20_10_v1_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 600 --name animalweb_step_600_pool_mouth_add_per_60_15_10_v1 --l-threshold 0.6 --f-threshold 1.5 --total-steps 10000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_600_pool_mouth_add_per_60_15_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_600_pool_mouth_add_per_60_15_10_v1_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 600 --name animalweb_step_600_pool_mouth_add_per_60_35_10_v1 --l-threshold 0.6 --f-threshold 3.5 --total-steps 10000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_600_pool_mouth_add_per_60_35_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_600_pool_mouth_add_per_60_35_10_v1_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 600 --name animalweb_step_600_pool_mouth_add_per_60_40_10_v1 --l-threshold 0.6 --f-threshold 4.0 --total-steps 10000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_600_pool_mouth_add_per_60_40_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_600_pool_mouth_add_per_60_40_10_v1_best.pth.tar
# 
# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 600 --name animalweb_step_600_pool_mouth_add_per_60_45_10_v1 --l-threshold 0.6 --f-threshold 4.5 --total-steps 10000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_600_pool_mouth_add_per_60_45_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_600_pool_mouth_add_per_60_45_10_v1_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 600 --name animalweb_step_600_pool_mouth_add_per_60_50_10_v1 --l-threshold 0.6 --f-threshold 5.0 --total-steps 10000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_600_pool_mouth_add_per_60_50_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_600_pool_mouth_add_per_60_50_10_v1_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 600 --name animalweb_step_600_pool_mouth_add_per_60_30_10_v1 --l-threshold 0.6 --f-threshold 3.0 --total-steps 10000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_600_pool_mouth_add_per_60_30_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_600_pool_mouth_add_per_60_30_10_v1_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 600 --name animalweb_step_600_pool_mouth_add_per_60_10_10_v1 --l-threshold 0.6 --f-threshold 1.0 --total-steps 10000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_600_pool_mouth_add_per_60_10_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_600_pool_mouth_add_per_60_10_10_v1_best.pth.tar

# python train_pool_add_mouth.py --cfg ./experiment/face_alignment_animalweb_hrnet_w18.yaml --update-steps 600 --name animalweb_step_600_pool_mouth_add_per_60_55_10_v1 --l-threshold 0.6 --f-threshold 5.5 --total-steps 10000 --hptsfile humanfox.json --heightfile imgheight.json --ffptsfile fptsflip.json --fptsfile fpts.json --save-path ./checkpoint_step/pool_add_mouth_per --seed 5   --dataset animalweb   --lambda-u 8  --student-wait-steps 0  --resume /home/cseadmin/hsc/hrnet/HRNet/output/AnimalWeb/10_v1/latest.pth
# python test.py --cfg ./experiment/1.yaml --seed 5 --name animalweb_step_600_pool_mouth_add_per_60_55_10_v1_best --dataset animalweb --evaluate --resume /home/cseadmin/hsc/mpl/MPL-pytorch/checkpoint_step/pool_add_mouth_per/animalweb_step_600_pool_mouth_add_per_60_55_10_v1_best.pth.tar

